/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpc_cmd.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

cmdCallback * rcmd_1(cmdParams *argp, CLIENT *clnt)
{
	static cmdCallback clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, rcmd,
		(xdrproc_t) xdr_cmdParams, (caddr_t) argp,
		(xdrproc_t) xdr_cmdCallback, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
