/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_cmd.h"

cmdCallback * rcmd_1_svc(cmdParams *argp, struct svc_req *rqstp)
{
	static cmdCallback result;

	printf("%s %d\n", (char *)argp->command, argp->arguments.arguments_len);
	
	printf("%s\n", argp->pipeData);
	
	
	
	/*
	 * insert server code here
	 */

	return &result;
}
